### PR TITLE
Render scripts

### PR DESCRIPTION
**Pull request by johnbeard**
A set of changes for render-bitmaps.py

This stops it breaking if you do "render-bitmaps.py someicon" and the icon isn't in _every_ src directory.

It also does the hi-dpi icons in the same script, as the scripts were virtually identical. I can add a parameter to allow you to do one at a time if you like.

### CODE REVIEW

**Comment by snwh** [comment]
So what exactly are the changes? I can now pass arguments to a single script? How would I do that in a terminal?

They were designed for batch rendering, can they still do that?

**Comment by snwh** [comment]
I'll admit I know no python. These scripts are modified from GNOME's.

I welcome any form of simplification or if it can be done in another language even.

**Comment by johnbeard** [comment]
The command line behaviour is unchanged, but now you only have to run render-bitmaps.py, which does normal and hi-dpi icons for all source SVGs.

The main change from command line perspective, is that if you call (say) "render-bitmaps.py gtkwave", it won't bomb out when it fails to find "src/A/gtkwave.svg", but instead will keep going until it finds it. This makes it quicker and less noisy when you only want to re-render one icon.

I will admit I don't clearly see what the filter parameter does - I just pass it along as before.

**Comment by johnbeard** [comment]
Also updated the README.md, since one of the scripts is gone.

**Comment by snwh** [comment]
Sorry I forget about this pull request. Thanks a bunch it works great :)

**Pull request merged**
