### PR TITLE
Ubuntu Budgie Logo

### PR DESCRIPTION
**Pull request by Foggalong**
Added the distributor logo for Ubuntu Budgie which is used in the welcome app. The current icon name is `*-budgie-remix` but will soon be renamed to `*-ubuntu-budgie`, hence the symlink.

### CODE REVIEW

**Comment by snwh** [comment]
There are rarely internal shadows on a Moka icon emblem. i.e. the logo should have a 1px 20 opacity drop shadow instead of an internal one.

**Comment by Foggalong** [comment]
The thinking was that because the baseplate and the budgie swirls had the same colour, it should be arranged so that the white circle is the emblem with cutouts (in keeping with the structure of the GNOME Software icon).
screenshot_2017-01-30_17-29-23
So the budgie logos are actually cutouts from the white with the baseplate showing through, rather than symbols over the top of the circle.
screenshot_2017-01-30_17-35-41

**Comment by snwh** [comment]
Those icons are exceptions. ;) Note they have a white background, so the shadow is more noticeable due to the contrast between the emblem and the background. Light/white emblems on a dark background get a drop-shadow for Moka icons, if it's a coloured/dark emblem on a light/white background it may get an inset shadow. Using an inset shadow on an emblem with a dark background reduces edge contrast.

**Comment by HEXcube** [comment]
@snwh  So something like this, u mean? :confused: 

distributor-logo-ubuntu-budgie-512

For the drop shadow, I duplicated the main symbol,colored it black, displaced 1 pixel to the bottom and set opacity as 0.20

**Comment by Foggalong** [comment]
@snwh Ah okay, no worries! What you say about it being a like background definitely makes sense. Happy to modify it to a version like the one @HEXcube suggested if that would be more fitting?

**Comment by snwh** [comment]
@HEXcube yep, like 95% of the other icons. ;)

**Comment by Foggalong** [comment]
@snwh No worries, then, I'll update this pr tonight so that it's consistent :)

**Comment by HEXcube** [comment]
> @HEXcube yep, like 95% of the other icons. ;)

Happy to hear that Sam! :relaxed:

**Comment by HEXcube** [comment]
Here's the source (Optimized SVG) incase you need it Joshua:

Link to SVG

```svg
<?xml version="1.0" encoding="UTF-8"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->
<svg enable-background="new" version="1.0" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <title>distributor-logo-ubuntu-budgie</title>
  <defs>
    <linearGradient id="linearGradient4254" x1="35" x2="253" y1="156" y2="156" gradientTransform="rotate(-90,122,150)" gradientUnits="userSpaceOnUse">
      <stop stop-color="#2e323c" offset="0"/>
      <stop stop-color="#404552" offset="1"/>
    </linearGradient>
  </defs>
  <metadata>
    <rdf:RDF>
      <cc:Work rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/>
        <dc:creator>
          <cc:Agent>
            <dc:title>Joshua "Foggalong" Fogg</dc:title>
          </cc:Agent>
        </dc:creator>
        <dc:source>Moka Icon Theme</dc:source>
        <cc:license rdf:resource="http://creativecommons.org/licenses/by-sa/4.0/"/>
        <dc:title>distributor-logo-ubuntu-budgie</dc:title>
        <dc:subject>
          <rdf:Bag/>
        </dc:subject>
        <dc:date/>
        <dc:rights>
          <cc:Agent>
            <dc:title/>
          </cc:Agent>
        </dc:rights>
        <dc:publisher>
          <cc:Agent>
            <dc:title/>
          </cc:Agent>
        </dc:publisher>
        <dc:identifier/>
        <dc:relation/>
        <dc:language/>
        <dc:coverage/>
        <dc:description/>
        <dc:contributor>
          <cc:Agent>
            <dc:title/>
          </cc:Agent>
        </dc:contributor>
      </cc:Work>
      <cc:Work rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/>
      </cc:Work>
      <cc:License rdf:about="http://creativecommons.org/licenses/by-sa/4.0/">
        <cc:permits rdf:resource="http://creativecommons.org/ns#Reproduction"/>
        <cc:permits rdf:resource="http://creativecommons.org/ns#Distribution"/>
        <cc:requires rdf:resource="http://creativecommons.org/ns#Notice"/>
        <cc:requires rdf:resource="http://creativecommons.org/ns#Attribution"/>
        <cc:permits rdf:resource="http://creativecommons.org/ns#DerivativeWorks"/>
        <cc:requires rdf:resource="http://creativecommons.org/ns#ShareAlike"/>
      </cc:License>
    </rdf:RDF>
  </metadata>
  <rect width="256" height="256" enable-background="accumulate" opacity="0"/>
  <rect x="18" y="19" width="220" height="220" rx="50" ry="50" color="#bebebe" enable-background="accumulate" opacity=".1"/>
  <path d="m68 18.5c-27.431 0-49.5 22.069-49.5 49.5v120c0 27.431 22.069 49.5 49.5 49.5h120c27.431 0 49.5-22.069 49.5-49.5v-120c0-27.431-22.069-49.5-49.5-49.5z" color="#bebebe" enable-background="accumulate" fill="url(#linearGradient4254)"/>
  <path d="m128 60a70 70 0 0 0 -70 70 70 70 0 0 0 70 70 70 70 0 0 0 70 -70 70 70 0 0 0 -70 -70zm18.73 16.38c1.98-0.05 3.61 0.18 5.57 0.5 7.13 1.15 14.02 5.74 18.39 13.31 5.9 10.22 4.51 23.16-2.1 30.26-3.58 3.3-4.33 3.55-6.56 5.05 1.52-2.38 1.79-2.84 2.15-5.03-0.08-1.23-0.05-1.74-0.69-3.39-1.17-2.26-2.06-3.15-3.97-4.28-2.47-1.11-4.57-1.24-6.16-1.23-1.24 0.01-2.01-0.05-3.67 0.22-7.67 2.11-16.27-0.85-20.31-7.85h-0.01c-4.83-8.37-1.3-19.45 7.35-24.45 2.56-1.47 5.1-2.63 7.89-2.95 0.76-0.09 1.46-0.14 2.12-0.16zm-50.94 22.77c1.24 0.04 2.46 0.2 3.65 0.47 4.65 1.45 5.23 1.98 7.65 3.16-2.83-0.13-3.36-0.14-5.43 0.65-1.03 0.68-1.48 0.91-2.59 2.29-1.38 2.15-1.71 3.36-1.73 5.59 0.28 2.68 1.22 4.57 2.02 5.95 0.62 1.06 0.96 1.75 2.02 3.06 5.67 5.59 7.4 14.51 3.36 21.52h0.01c-4.84 8.37-16.2 10.85-24.857 5.86-2.55-1.48-4.824-3.1-6.498-5.35-1.837-2.47-2.611-4.37-3.551-6.84-2.571-6.75-2.041-15.01 2.332-22.58 5.162-8.94 14.924-14.09 23.614-13.78zm54.09 45.06c9.66 0 17.5 8.6 17.5 18.6-0.01 2.94-0.28 5.72-1.39 8.3-1.22 2.83-2.47 4.44-4.14 6.49-4.56 5.6-11.98 9.28-20.73 9.28-11.79 0-22.31-7.68-25.15-16.96-1.07-4.75-0.91-5.52-1.09-8.2 1.3 2.51 1.56 2.97 3.28 4.37 1.1 0.55 1.53 0.83 3.28 1.1 2.54 0.12 3.76-0.21 5.7-1.3 2.18-1.58 3.35-3.34 4.14-4.72 0.61-1.07 1.04-1.71 1.64-3.28 2.01-7.7 8.87-13.67 16.96-13.67z" enable-background="new" fill-opacity=".2"/>
  <path d="m128 58a70 70 0 0 0 -70 70 70 70 0 0 0 70 70 70 70 0 0 0 70 -70 70 70 0 0 0 -70 -70zm18.73 16.38c1.98-0.05 3.61 0.18 5.57 0.5 7.13 1.15 14.02 5.74 18.39 13.31 5.9 10.22 4.51 23.16-2.1 30.26-3.58 3.3-4.33 3.55-6.56 5.05 1.52-2.38 1.79-2.84 2.15-5.03-0.08-1.23-0.05-1.74-0.69-3.39-1.17-2.26-2.06-3.15-3.97-4.28-2.47-1.11-4.57-1.24-6.16-1.23-1.24 0.01-2.01-0.05-3.67 0.22-7.67 2.11-16.27-0.85-20.31-7.85h-0.01c-4.83-8.37-1.3-19.45 7.35-24.45 2.56-1.47 5.1-2.63 7.89-2.95 0.76-0.09 1.46-0.14 2.12-0.16zm-50.94 22.77c1.24 0.04 2.46 0.2 3.65 0.47 4.65 1.45 5.23 1.98 7.65 3.16-2.83-0.13-3.36-0.14-5.43 0.65-1.03 0.68-1.48 0.91-2.59 2.29-1.38 2.15-1.71 3.36-1.73 5.59 0.28 2.68 1.22 4.57 2.02 5.95 0.62 1.06 0.96 1.75 2.02 3.06 5.67 5.59 7.4 14.51 3.36 21.52h0.01c-4.84 8.37-16.2 10.85-24.857 5.86-2.55-1.48-4.824-3.1-6.498-5.35-1.837-2.47-2.611-4.37-3.551-6.84-2.571-6.75-2.041-15.01 2.332-22.58 5.162-8.94 14.924-14.09 23.614-13.78zm54.09 45.06c9.66 0 17.5 8.6 17.5 18.6-0.01 2.94-0.28 5.72-1.39 8.3-1.22 2.83-2.47 4.44-4.14 6.49-4.56 5.6-11.98 9.28-20.73 9.28-11.79 0-22.31-7.68-25.15-16.96-1.07-4.75-0.91-5.52-1.09-8.2 1.3 2.51 1.56 2.97 3.28 4.37 1.1 0.55 1.53 0.83 3.28 1.1 2.54 0.12 3.76-0.21 5.7-1.3 2.18-1.58 3.35-3.34 4.14-4.72 0.61-1.07 1.04-1.71 1.64-3.28 2.01-7.7 8.87-13.67 16.96-13.67z" enable-background="new" fill="#ebebeb"/>
  <path d="m68 19c-27.163 0-49 21.837-49 49v1c0-27.163 21.837-49 49-49h120c27.163 0 49 21.837 49 49v-1c0-27.163-21.837-49-49-49z" color="#bebebe" enable-background="accumulate" fill="#fff" opacity=".13"/>
  <path d="m188 238c27.163 0 49-21.837 49-49v-1c0 27.163-21.837 49-49 49h-120c-27.163 0-49-21.837-49-49v1c0 27.163 21.837 49 49 49z" color="#bebebe" enable-background="accumulate" opacity=".5"/>
  <path d="m68 237c-27.163 0-49-21.837-49-49v-1c0 27.163 21.837 49 49 49h120c27.163 0 49-21.837 49-49v1c0 27.163-21.837 49-49 49z" color="#bebebe" enable-background="accumulate" fill="#fff" opacity=".1"/>
  <path d="m68 18c-27.7 0-50 22.3-50 50v120c0 27.7 22.3 50 50 50h120c27.7 0 50-22.3 50-50v-120c0-27.7-22.3-50-50-50zm0 1h120c27.163 0 49 21.837 49 49v120c0 27.163-21.837 49-49 49h-120c-27.163 0-49-21.837-49-49v-120c0-27.163 21.837-49 49-49z" color="#bebebe" enable-background="accumulate" opacity=".41"/>
</svg>
```

**Pull request merged**
